#!/usr/bin/env bash

CONFIG="/home/louhmmsb/Documents/Configs"
MODE=""

if [ $# -eq 1 ]
then
	MODE=$1
fi

# ln -sf $CONFIG/ALACRITTY/alacritty$1.yml $HOME/.config/alacritty.yml
ln -sf $CONFIG/TMUX/.tmux.conf $HOME/.tmux.conf
ln -sf $CONFIG/ZSH/.zshrc$1 $HOME/.zshrc
ln -sf $CONFIG/KITTY $HOME/.config/kitty
ln -sf $CONFIG/I3 $HOME/.config/i3
ln -sf $CONFIG/ROFI $HOME/.config/rofi
rm -rf $HOME/.config/zathura
mkdir $HOME/.config/zathura
ln -sf $CONFIG/zathura/zathurarc $HOME/.config/zathura/zathurarc
ln -sf $CONFIG/.fonts $HOME/.fonts
ln -sf $CONFIG/GIT/.gitconfig $HOME/.gitconfig
