#!/usr/bin/env bash

CONFIG="/home/louhmmsb/Documents/Configs"
MODE=""

if [ $# -eq 1 ]
then
	MODE=$1
fi

MODE="TWM" #Always using this from now on :)

# ln -sf $CONFIG/ALACRITTY/alacritty$1.yml $HOME/.config/alacritty.yml
ln -sf $CONFIG/TMUX/.tmux.conf $HOME/.tmux.conf
ln -sf $CONFIG/ZSH/.zshrc$MODE $HOME/.zshrc
rm -rf $HOME/.config/kitty
ln -sf $CONFIG/KITTY $HOME/.config/kitty
rm -rf $HOME/.config/i3
ln -sf $CONFIG/I3 $HOME/.config/i3
rm -rf $HOME/.config/rofi
ln -sf $CONFIG/ROFI $HOME/.config/rofi
rm -rf $HOME/.config/zathura
mkdir $HOME/.config/zathura
ln -sf $CONFIG/ZATHURA/zathurarc $HOME/.config/zathura/zathurarc
ln -sf $CONFIG/.fonts $HOME/.fonts
ln -sf $CONFIG/GIT/.gitconfig $HOME/.gitconfig
rm -rf $HOME/.config/polybar
ln -sf $CONFIG/POLYBAR $HOME/.config/polybar
rm -rf $HOME/.config/nvim
ln -sf $CONFIG/NVIM $HOME/.config/nvim
ln -sf $CONFIG/STARSHIP/starship.toml $HOME/.config/starship.toml
