env:

  TERM: xterm-256color

window:

  padding:
    x: 10
    y: 10

  # Spread additional padding evenly around the terminal content.
  dynamic_padding: true

  # Window title
  title: Alacritty

  # Window class (Linux/BSD only):
  class:
    # Application instance name
    instance: Alacritty
    # General application class
    general: Alacritty

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 5000


# Font configuration
font:
  # Normal (roman) font face
  normal:
    family: MesloLGS NF
    style: Regular

  # Bold font face
  bold:
    family: MesloLGS NF
    style: Bold

  # Italic font face
  italic:
    family: MesloLGS NF
    style: Italic

  # Bold italic font face
  bold_italic:
    family: MesloLGS NF
    style: Bold Italic

  # Point size
  size: 11.0

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 4

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the right,
  # increasing `y` moves the glyph upwards.
  glyph_offset:
    x: 0
    y: 4


# Colors (Tomorrow Night Bright)
colors:
  # Default colors
  primary:
    background: '0x050505'
    foreground: '0xEEEEEE'
    selection:
    text: '0x282a36'

  # Normal colors
  normal:
    black:   '0x282A36'
    red:     '0xF37F97'
    green:   '0x5ae6b4'
    yellow:  '0xf7ca7a'
    blue:    '0x8297f4'
    magenta: '0xea8bff'
    cyan:    '0x79e6f3'
    white:   '0xEEEEEE'

  # Bright colors
  bright:
    black:   '0x414458'
    red:     '0xffa3c3'
    green:   '0x9be6cb'
    yellow:  '0xffe7a9'
    blue:    '0x8ab1ff'
    magenta: '0xf59cff'
    cyan:    '0xa2ffff'
    white:   '0xbebec1'


background_opacity: 1.0
